#Matcthes can be inverted with ^ in front of the identifier

["^WhiteSpace Locate"]
group = "all"

["ParameterIdentifier ^WhiteSpace Locate"]
group = "denshiParameter"

["DataType Keyword ^WhiteSpace Locate"]
group = "denshiKeyword"


